{
 "title": "Photovoltaik Raspi",
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "title": "Gesamteinspeißung am letzten Tag im Zeitraum / Heute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max(increase(sma_feeding_energy_total[1d])) by (serial))",
     "legendFormat": "Summe"
    },
    {
     "expr": "max(increase(sma_feeding_energy_total[1d])) by (serial)",
     "legendFormat": "SN: {{serial}}"
    }
   ]
  },
  {
   "title": "Gesamteinspeißung seit 2011",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max(max_over_time(sma_feeding_energy_total[90d])) by (serial))",
     "legendFormat": "Summe"
    },
    {
     "expr": "max(max_over_time(sma_feeding_energy_total[90d])) by (serial)",
     "legendFormat": "SN: {{serial}}"
    }
   ]
  },
  {
   "title": "kWh/Tag im Zeitraum",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(max(increase(sma_feeding_energy_total[1d])) by (serial))"
    }
   ]
  },
  {
   "title": "Gesamteinspeißung im Zeitraum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max(increase(sma_feeding_energy_total[$__interval])) by (serial))",
     "legendFormat": "Summe"
    },
    {
     "expr": "max(increase(sma_feeding_energy_total[$__interval])) by (serial)",
     "legendFormat": "SN: {{serial}}"
    }
   ]
  },
  {
   "title": "kWh/Tag im Zeitraum",
   "type": "graph",
   "gridPos": { "h": 16, "w": 19, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(max(increase(sma_feeding_energy_total[$__interval])) by (serial))",
     "legendFormat": "Summe"
    },
    {
     "expr": "max(increase(sma_feeding_energy_total{}[$__interval])) by (serial)",
     "legendFormat": "{{serial}}"
    }
   ]
  }
 ]
}